記述子一覧
<pre>%p  [path]                  入力画像ファイルのパス
%D  [drive]                 入力画像ファイルのドライブ名
%P  [path without drive]    入力画像ファイルのパスからドライブ名を除いたもの
%r  [rightmost directory]   入力画像ファイルの存在するディレクトリ名
%n  [name]                  入力画像ファイル名(拡張子を除いたもの)
%e  [extension]             入力画像ファイルの拡張子
%w  [source width]          入力画像の幅
%h  [source height]         入力画像の高さ
%x  [object width]          出力画像の幅
%y  [object height]         出力画像の高さ
%t  [time]                  入力画像の更新時刻
%s  [size]                  入力画像のファイルサイズ
%2  [2 prec order]          処理の通し番号(0から始まり、精度2桁) (1～9まで可)
%a  [app path]              wisteria.exe のパス
%d  [desktop path]          デスクトップのパス
%m  [my documents path]     マイドキュメントのパス
%j  [jpeg quality]          JPEG 出力時の画質
%f  [function type]         補間法の種類
%v  [values]                各種フィルタの設定
%c  [current time]          現在時刻
%Eo [original date time]    撮影時刻(EXIF)
%Em [model name]            機種名(EXIF)
%%  [%]                     '%'の文字自体

@n  [new line]              改行
@s  [source url]            入力画像の URL
@o  [object url]            出力画像の URL
@q  [quantity]              入力画像の数
@@  [@]                     '@'の文字自体</pre>