開発環境
<dl>
<dt>OS</dt>
<dd>Windows XP Media Center Edition 2002 Service Pack 3</dd>

<dt>PC</dt>
<dd>Aero Stream B31J-6430E (ASUS P5LD2-VM R2.0)</dd>

<dt>Monitor</dt>
<dd>NEC LCD194WXM (19インチワイドディスプレイ 1440*900 32bpp)</dd>

<dt>CPU</dt>
<dd>Intel Core2 Duo E6400 (2.13GHz)</dd>

<dt>Chipset</dt>
<dd>Intel 945G Express</dd>

<dt>Memory</dt>
<dd>PC5300 DDR-2 SDRAM CL5 2GBx2</dd>

<dt>Video</dt>
<dd>GMA 950 (Intel 945G Express 内蔵)</dd>

<dt>Sound</dt>
<dd>YST-M45D (USB スピーカー)</dd>

<dt>Compiler</dt>
<dd>Delphi XE2 Professional Update 4</dd>
<dd>Turbo Delphi Explorer for Win32 update2</dd>
<dd>Visual Studio 2008 Standard Edition Service Pack 1</dd>
<dd>Visual Studio 2005 Standard Edition Service Pack 1</dd>
<dd>MinGW GCC 3.4.5</dd>
<dd>HTML Help Workshop 1.32</dd>
</dl>