開発環境
<dl>
<dt>OS</dt>
<dd>Windows 10 Pro 64bit</dd>

<dt>PC</dt>
<dd>AeroSlim RS3J-B180/T (ASRock H310M-HDV/M.2)</dd>

<dt>Monitor</dt>
<dd>EIZO FlexScan EV2360-WT (22.5インチワイドディスプレイ 1920*1200 32bpp)</dd>

<dt>CPU</dt>
<dd>Intel Core i3-8100 (3.60GHz)</dd>

<dt>Chipset</dt>
<dd>Intel H310 Express</dd>

<dt>Memory</dt>
<dd>PC4-19200 DDR4 SDRAM 8GBx2</dd>

<dt>Video</dt>
<dd>Intel UHD Graphics 630 (Intel Core i3-8100 内蔵)</dd>

<dt>Sound</dt>
<dd>YST-M45D (USB スピーカー)</dd>

<dt>Compiler</dt>
<dd>Delphi 10.3 Update 3</dd>
<dd>Delphi XE2 Professional Update 4 HotFix 1</dd>
<dd>Delphi 2007 December Update</dd>
<dd>MinGW GCC 3.4.5</dd>
</dl>
