<dl>
<dt>マニュアル</dt>
<dd>
<ul>
<li><a href="introduction.html">初めに</a></li>
<li><a href="usage.html">使い方</a></li>
<li><a href="descriptor.html">記述子一覧</a></li>
<li><a href="hidden.html">隠し設定</a></li>
<li><a href="history4x.html">更新履歴 (v4.x)</a></li>
<li><a href="history3x.html">更新履歴 (v3.x)</a></li>
<li><a href="history2x.html">更新履歴 (v2.x)</a></li>
<li><a href="history1x.html">更新履歴 (v1.x)</a></li>
</ul>
</dd>
<dt>お読みください</dt>
<dd>
<ul>
<li><a href="disclaimer.html">免責</a></li>
<li><a href="dev-env.html">開発環境</a></li>
<li><a href="support.html">サポート</a></li>
<li><a href="etc.html">その他</a></li>
</ul>
</dd>
<dt>連絡先</dt>
<dd>
<ul>
<li><a href="http://hp.vector.co.jp/authors/VA015850/">ホームページ</a></li>
<li><a href="http://leafel.bbs.fc2.com/">掲示板</a></li>
<li><a href="https://twitter.com/c_nyan">Twitter</a></li>
<li><a href="mailto:recv@cyanet.jp">メールアドレス</a></li>
</ul>
</dd>
</dl>