使い方
<h2>処理の開始</h2>
<p>サイズ指定をして画像又はフォルダをドラッグするだけです.
実行ファイル(及びショートカット)ではなく、起動したウインドウへドラッグしてください.</p>

<h2>サイズ指定</h2>
<p>エディットボックスは四則演算式をサポートしています.</p>
<p>サイズの違う全ての画像の高さや幅を一致させたい場合は絶対指定にして、
縦横比の保存をチェックして、縦横比の基準を揃えたい方に変更してください.</p>
<p>長辺基準は指定した幅と高さに収まる最大サイズへの変換、短辺基準は指定した幅と高さを越える最小サイズへの変換となります.</p>

<h2>ファイル名の生成規則</h2>
<p>%系の記述子が使えます.</p>

<h2>読込形式</h2>
<p>以下の画像形式に対応しています. また、Susie プラグインにより拡張できます.</p>
<ul>
<li>Windows Bitmap (拡張子: bmp)</li>
<li>JPEG (拡張子: jpeg, jpg)</li>
<li>Graphics Interchange Format (拡張子: gif)</li>
<li>Portable Network Graphics (拡張子: png)</li>
<li>Windows Icon (拡張子: ico)</li>
<li>Tagged Image File Format (拡張子: tiff, tif)</li>
<li>JPEG XR (旧称 HD Photo / Windows Media Photo) (拡張子: jxr, hdp, wdp)</li>
</ul>

<h2>出力形式</h2>
<p>以下の画像形式に対応しています. また、A to B Convertor プラグインにより拡張できます(32bit 版のみ).</p>
<ul>
<li>Windows Bitmap (拡張子: bmp)</li>
<li>JPEG (拡張子: jpeg, jpg)</li>
<li>Graphics Interchange Format (拡張子: gif)</li>
<li>Portable Network Graphics (拡張子: png)</li>
<li>Portable Pixmap Format (P3 / ASCII) (拡張子: pnm, ppm)</li>
<li>Photoshop 3.0 (拡張子: psd)</li>
</ul>
<p>また、拡張子として png8, bmp8 を指定した場合は256色に、png4, bmp4 を指定した場合には16色で、png, bmp として出力します(必要であれば減色します).</p>

<h2>雛型</h2>
<p>雛型の実体は samples ディレクトリにある *.ini です.
自分の設定を追加したい場合は map.ini を修正してください.</p>

<h2>Susie Plug-in</h2>
<p>Susie Plug-in に対応しています.
使いたいプラグインを wisteria.exe と同じディレクトリに入れてください.</p>

<h2>HTML 出力</h2>
<p>HTML 出力をカスタマイズしたい場合には、samples ディレクトリの HTML 出力関係の設定ファイルを参考にしてください.
HTML に関する知識があれば、記述子一覧を見ることで大体やり方が分ると思います.</p>
<p>Nth アイテム毎に OnNth が発生します.
アイテム数が Nth で割り切れない場合、OnEnd の前に足りない分だけ OnRemain が発生します.
OnItem 以外の OnXXX で使える記述子は @n, @@, %% のみです.</p>

<h2>効果</h2>
<p>処理順は 切り取り → 反転 → 回転 → ガンマ補正 → 正規化 → 輝度補正 → コントラスト補正 → ノイズ除去 → 拡大縮小 → 輪郭強調 → 白黒化 です.
効果メニューは処理順に並べてあります.</p>

<h2>起動時引数の利用法</h2>
<ol>
<li>藤を起動して設定を行い「文書 → 設定の保存」で設定を保存.</li>
<li>wisteria.exe のショートカットを作る.</li>
<li>ショートカットのプロパティーのリンク先の第1引数に1で作った設定を指定.<br />
(例: "c:\resizer\wisteria.exe" "c:\resizer\custom.ini")</li>
<li>後はショートカットに画像ファイルをドロップしてください.<br />
(ショートカットを送る(SendTo)やデスクトップに置くと便利でしょう)</li>
</ol>
<p>普通にコマンドラインで指定することも可能です.<br />
(例: "c:\resizer\wisteria.exe" "c:\resizer\custom.ini" "c:\a.jpg" "c:\b.jpg" "c:\c.jpg")</p>

<h2>各種フィルタの補正式</h2>
<dl>
<dt>ガンマ補正: (X / 255) ^ V * 255</dt>
<dd>Windows のガンマ値(2.2)を Mac のガンマ値(1.8) にするなら V=0.82</dd>
<dt>正規化: (Luma - LumaMin) * (Max - Min) / (LumaMax - LumiMin) + Min</dt>
<dd>LumaMin と LumaMax は入力画像の最大輝度と最小輝度.</dd>
<dd>従来の正規化は Min=0, Max=255</dd>
<dt>輝度補正: Luma * ((Max - Min) / 255) + Min</dt>
<dd>単純に輝度を +20 するなら Min=20, Max=275</dd>
<dd>普通は飽和を気にして Min=40, Max=255 とか</dd>
<dt>コントラスト補正: (X - 127.5) * V + 127.5</dt>
<dd>コントラストを強める場合は V を1より大きく、弱める場合は V を1より小さく(V は 0 より大きい小数)</dd>
</dl>

<h2>白黒化の設定に対する輝度の計算式</h2>
<dl>
<dt>0</dt>
<dd>BT.601、すなわち Y = 0.299 * R + 0.587 * G + 0.114 * B.</dd>
<dt>1</dt>
<dd>BT.709、すなわち Y =  0.2125 * R ＋ 0.7154 * G ＋ 0.0721 * B.</dd>
<dt>2</dt>
<dd>Y = R.</dd>
</dl>